network:
  dns_servers:
  - 8.8.8.8
  - 1.1.1.1
nodes:
  disk_size: 30
  storage_pool_name: "storage_pool"
  control:
    cpu: 2
    memory: 4096
  workers:
    count: 1
    cpu: 2
    memory: 4096
software:
  box: debian/bookworm64
