frontend:
  image:
    repository: 
    tag: latest
  replicaCount: 2
  service:
    name: frontend-service
    port: 80

api:
  image:
    repository: your-api-image
    tag: latest
  replicaCount: 2
  service:
    name: api-service
    port: 8080

database:
  image:
    repository: mongo
    tag: latest
  replicaCount: 2
  service:
    name: database-service
    port: 27017