## must be specified
# cf:
#   CF_API_EMAIL:
#   CF_API_KEY:

traefik:
  additionalArguments:
    - --accesslog
    - --providers.kubernetescrd
    - --entrypoints.websecure.Address=:443
    - --entrypoints.websecure.http.tls.certresolver=cloudflare
    - --entrypoints.websecure.http.tls.domains[0].main=site.348575.xyz
    - --entrypoints.websecure.http.tls.domains[0].main=api.348575.xyz
    - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
    - --certificatesresolvers.cloudflare.acme.email=kjosephsubash@gmail.com
    - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53
    - --certificatesresolvers.cloudflare.acme.storage=/certs/acme.json

  logs:
    general:
      level: ERROR

  ports:
    web:
      redirectTo:
        port: websecure
    websecure:
      port: 443

  ingressRoute:
    dashboard:
      enabled: true

  env:
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        key: email
        name: cloudflare-api-credentials
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        key: apiKey
        name: cloudflare-api-credentials
  - name: CF_ZONE_API_TOKEN
    valueFrom:
      secretKeyRef:
        key: apiKey
        name: cloudflare-api-credentials

  persistence:
    enabled: true
    path: /certs
    size: 128Mi

## must be specified
hosts:
  site: site.348575.xyz
  api: api.348575.xyz
  content: content.348575.xyz

frontend:
  image: 192.168.121.237:30000/studuwo/frontend
  replicas: 2
  containerPort: 80
  service:
    name: frontend-service
    port: 80
    targetPort: 80

api:
  image:
    repository: 192.168.121.237:30000/studuwo/api # should specify
    tag: latest
  replicas: 2
  containerPort: 8080
  service:
    name: api-service
    port: 8080
    targetPort: 5000

database:
  image: postgres
  replicas: 1
  containerPort: 5432
  accessModes: ReadWriteMany
  persistentVolume:
    storage: 1Gi
    hostPath: /postgres-data # Change this 
  persistentVolumeClaim:
    storage: 1Gi
  service:
    name: database-service
    port: 5432
    targetPort: 5432
  # POSTGRES_USERNAME:
  # POSTGRES_PASSWORD:

seaweedfs:
  filer:
    s3:
      enabled: true
      skipAuthSecretCreation: true
      existingConfigSecret: seaweed-s3-secret

# seaweed:
#   admin:
#     accessKey:
#     secretKey:
#   open:
#     accessKey:
#     secretKey: