## must be specified
hosts:
  site: studuwo.348575.xyz
  api: sd-api.348575.xyz

site:
  image: docker-registry.348575.xyz/studuwo/site:1.0.3
  replicas: 4
  containerPort: 80
  service:
    name: site-service
    port: 80
    targetPort: 80

api:
  image: docker-registry.348575.xyz/studuwo/api:1.0.15
  replicas: 4
  containerPort: 5000
  service:
    name: api-service
    port: 443
    targetPort: 443

api_canary:
  image: docker-registry.348575.xyz/studuwo/api:1.0.16
  replicas: 2
  containerPort: 5000
  service:
    name: api-service
    port: 443
    targetPort: 443

sp:
  image: docker-registry.348575.xyz/studuwo/seaweed-proxy:1.0.10
  replicas: 2
  containerPort: 5000
  service:
    name: seaweed-proxy-service
    port: 443
    targetPort: 443

database:
  image: postgres
  replicas: 1
  containerPort: 5432
  accessModes: ReadWriteOnce
  persistentVolume:
    storage: 1Gi
    hostPath: /postgres-data # Change this 
  persistentVolumeClaim:
    storage: 1Gi
  service:
    name: database-service
    port: 5432
    targetPort: 5432
  POSTGRES_USERNAME: c3R1ZHV3bw==
  POSTGRES_PASSWORD: dGVzdA==

seaweedfs:
  filer:
    data:
      type: "persistentVolumeClaim"
      size: "30Gi"
      storageClass: "standard-disk"
    logs:
      type: "persistentVolumeClaim"
      size: "1Gi"
      storageClass: "standard-disk"
    s3:
      enabled: true
      skipAuthSecretCreation: true
      existingConfigSecret: seaweed-s3-secret
  master:
    data:
      type: "persistentVolumeClaim"
      size: "30Gi"
      storageClass: "standard-disk"
    logs:
      type: "persistentVolumeClaim"
      size: "1Gi"
      storageClass: "standard-disk"
  volume:
    enabled: true
    data:
      type: "persistentVolumeClaim"
      size: "30Gi"
      storageClass: "standard-disk"
    dataDirs:
    - name: data1
      type: "persistentVolumeClaim"
      size: "30Gi"
      storageClass: "standard-disk"
    idx:
      type: "persistentVolumeClaim"
      size: "1Gi"
      storageClass: "standard-disk"
    logs:
      type: "persistentVolumeClaim"
      size: "1Gi"
      storageClass: "standard-disk"

# specify these
# seaweed:
#   admin:
#     accessKey:
#     secretKey:
#   open:
#     accessKey:
#     secretKey: