## must be specified
hosts:
  site: site.348575.xyz
  api: api.348575.xyz

site:
  image: registry.348575.xyz/studuwo/site:1.0.2
  replicas: 1
  containerPort: 80
  service:
    name: site-service
    port: 80
    targetPort: 80

api:
  image: registry.348575.xyz/studuwo/api:1.0.11
  replicas: 1
  containerPort: 5000
  service:
    name: api-service
    port: 443
    targetPort: 443

sp:
  image: registry.348575.xyz/studuwo/seaweed-proxy:1.0.8
  replicas: 1
  containerPort: 5000
  service:
    name: seaweed-proxy-service
    port: 80
    targetPort: 5000

database:
  image: postgres
  replicas: 1
  containerPort: 5432
  accessModes: ReadWriteMany
  persistentVolume:
    storage: 1Gi
    hostPath: /postgres-data # Change this 
  persistentVolumeClaim:
    storage: 1Gi
  service:
    name: database-service
    port: 5432
    targetPort: 5432
  # POSTGRES_USERNAME:
  # POSTGRES_PASSWORD:

seaweedfs:
  filer:
    s3:
      enabled: true
      skipAuthSecretCreation: true
      existingConfigSecret: seaweed-s3-secret

# seaweed:
#   admin:
#     accessKey:
#     secretKey:
#   open:
#     accessKey:
#     secretKey: