# must be specified
# cf:
#   CF_API_EMAIL:
#   CF_API_KEY:

traefik:
  additionalArguments:
    - --accesslog
    - --serversTransport.insecureSkipVerify=true
    - --providers.kubernetescrd
    - --entrypoints.web.Address=:8080
    - --entrypoints.websecure.Address=:8443
    - --entrypoints.websecure.http.tls.certresolver=cloudflare
    - --entrypoints.websecure.http.tls.domains[0].main=348575.xyz
    - --entrypoints.websecure.http.tls.domains[0].sans[0]=*348575.xyz
    - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
    - --certificatesresolvers.cloudflare.acme.email=kjosephsubash@gmail.com
    - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53
    - --certificatesresolvers.cloudflare.acme.storage=/tmp/acme.json

  logs:
    general:
      level: DEBUG

  ports:
    web:
      port: 8080
      redirectTo:
        port: websecure
    websecure:
      port: 8443

  ingressRoute:
    dashboard:
      enabled: false

  env:
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        key: email
        name: cloudflare-api-credentials
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        key: apiKey
        name: cloudflare-api-credentials
  - name: CF_ZONE_API_TOKEN
    valueFrom:
      secretKeyRef:
        key: apiKey
        name: cloudflare-api-credentials

  persistence:
    enabled: true
    path: /certs
    size: 128Mi
    storageClass: standard

  service:
    enabled: true
    type: LoadBalancer
    # specify this
    # loadBalancerIP:

## must be specified
hosts:
  registry: docker-registry.348575.xyz

docker-registry:
  replicaCount: 1
  persistence:
    enabled: true
    size: 30Gi
    deleteEnabled: true
    storageClass: standard-rwo
  # specify this
  # secrets:
  #   htpasswd:

cert-manager:
  installCRDs: true