# Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-tls
spec:
  secretName: cert-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
  - www.example.com # replace with our dns