# Front-End Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: {{.Values.frontend.replicas}}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{.Values.frontend.image}}
        ports:
        - containerPort: 80


# Back-End Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: {{.Values.api.replicas}}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: {{.Values.api.image.repository}}
        ports:
        - containerPort: 8080

# MongoDB Deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-deployment
spec:
  replicas: {{.Values.database.replicas}}
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      volumes:
      - name: Mongo-pv-storage
        persistentVolumeClaim:
          claimName: Mongo-pv-claim
      containers:
      - name: database
        image: {{.Values.database.image}}
        env:
        - name: MONGO_USERNAME
          valueFrom:
            configMapKeyRef:
              key: username
              name: mongodb-config
        - name: MONGO_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: password
              name: mongodb-config
        ports:
        - containerPort: 27017

# PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: Mongo-pv-storage
spec:
  capacity:
    storage: {{.Values.database.persistentVolume.storage}}
  accessModes: 
    - ReadWriteMany
  hostPath:
    path: {{.Values.database.persistentVolume.hostPath}}

# PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: Mongo-pv-claim
spec:
  accessModes:
    - {{.Values.database.accessModes}}
  resources:
    requests:
      storage: {{.Values.database.persistentVolumeClaim.storage}}
