# Front-End Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: {{.Values.frontend.replicas}}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{.Values.frontend.image}}
        ports:
        - containerPort: {{.Values.frontend.containerPort}}
---
# Back-End Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: {{.Values.api.replicas}}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: {{.Values.api.image.repository}}
        ports:
        - containerPort: {{.Values.api.containerPort}}
---
# MongoDB Deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-deployment
spec:
  replicas: {{.Values.database.replicas}}
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      volumes:
      - name: mongo-pv-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
      containers:
      - name: database
        image: {{.Values.database.image}}
        volumeMounts:
          - name: mongo-pv-storage
            mountPath: /data/db
        ports:
        - containerPort: {{.Values.database.containerPort}}
---
# PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-storage
spec:
  storageClassName: local-path
  capacity:
    storage: {{.Values.database.persistentVolume.storage}}
  accessModes: 
    - ReadWriteMany
  hostPath:
    path: {{.Values.database.persistentVolume.hostPath}}
---
# PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
spec:
  accessModes:
    - {{.Values.database.accessModes}}
  resources:
    requests:
      storage: {{.Values.database.persistentVolumeClaim.storage}}
