apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-canary
spec:
  replicas: {{.Values.api_canary.replicas}}
  selector:
    matchLabels:
      app: api
      version: v1.0.16
  template:
    metadata:
      labels:
        app: api
        version: v1.0.16
    spec:
      imagePullSecrets:
      - name: docker-registry.348575.xyz
      serviceAccountName: wait-for-deps
      initContainers:
      - name: wait-for-deps
        image: bitnami/kubectl
        args:
          - rollout
          - status
          - --watch
          - --timeout=600s
          - statefulset/database-deployment
      - name: gen-cert
        image: docker-registry.348575.xyz/studuwo/kubectl-envsubst:1.0.0 
        command:
          - /config/gen.sh
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SVC_NAME
          value: {{.Values.api_canary.service.name}}
        volumeMounts:
          - mountPath: /config
            name: gen-cert
          - mountPath: /gen-certs
            name: certs
      containers:
        - name: api
          image: {{.Values.api_canary.image}}
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: postgres-secret
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: postgres-secret
          - name: URI
            value: {{.Values.database.service.name}}
          ports:
          - containerPort: {{.Values.api_canary.containerPort}}
        - name: api-sidecar
          image: nginx
          volumeMounts:
            - mountPath: /gen-certs
              name: certs
            - mountPath: /etc/nginx/conf.d/
              name: nginx-conf
          ports:
          - containerPort: {{.Values.api_canary.service.targetPort}}
      volumes:
        - name: certs
          emptyDir: {}
        - name: gen-cert
          configMap:
            name: gen-cert
            items:
              - key: gen.sh
                path: gen.sh
                mode: 0777
              - key: config.yaml
                path: config.yaml
        - name: nginx-conf
          configMap:
            name: nginx-sidecar
            items:
              - key: default.conf
                path: default.conf