apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-credentials
  namespace: traefik

type: Opaque
stringData:
  email: {{ .Values.cf.CF_API_EMAIL }}
  apiKey: {{ .Values.cf.CF_API_KEY }}

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: site_api
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.hosts.site }}`) && PathPrefix(`/tls`)
    kind: Rule
    services:
    - name: frontend
      port: 80
  - match: Host(`{{ .Values.hosts.api }}`) && PathPrefix(`/tls`)
    kind: Rule
    services:
    - name: backend
      port: 80
  tls:
    certResolver: cloudflare