apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: site
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.hosts.site }}`)
    kind: Rule
    services:
      - name: frontend-service
        port: 80
  - match: Host(`{{ .Values.hosts.api }}`)
    kind: Rule
    services:
      - name: api-service
        port: 8080
  tls:
    certResolver: cloudflare
    domains:
      - main: "*.348575.xyz"
