# api to db only communication
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-db-policy
spec:
  podSelector:
    matchLabels:
      app: database
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: api
---
#only seaweed proxy can talk to seaweed  
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: swproxy-sw-policy
spec:
  podSelector:
    matchLabels:
      name: seaweedfs
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: seaweed-proxy
---
# api can only talk to proxy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-swproxy-policy
spec:
  podSelector:
    matchLabels:
      app: seaweed-proxy
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: api