apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  username: {{.Values.database.MONGO_USERNAME}}
  password: {{.Values.database.MONGO_PASSWORD}}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-credentials
type: Opaque
data:
  email: {{ .Values.cf.CF_API_EMAIL }}
  apiKey: {{ .Values.cf.CF_API_KEY }}