apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  username: {{.Values.database.POSTGRES_USERNAME}}
  password: {{.Values.database.POSTGRES_PASSWORD}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: seaweed-s3-secret
  namespace: default
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: s3
stringData:
  seaweedfs_s3_config: '{"identities":[{"name":"anvAdmin","credentials":[{"accessKey":"{{ .Values.seaweed.admin.accessKey }}","secretKey":"{{ .Values.seaweed.admin.secretKey }}"}],"actions":["Admin","Read","Write"]},{"name":"anvReadOnly","credentials":[{"accessKey":"{{ .Values.seaweed.open.accessKey }}","secretKey":"{{ .Values.seaweed.open.secretKey }}"}],"actions":["Read"]}]}'
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: seaweed-api-secret
stringData:
  accessKey: {{ .Values.seaweed.admin.accessKey }}
  secretKey: {{ .Values.seaweed.admin.secretKey }}