apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  username: {{.Values.database.MONGO_USERNAME}}
  password: {{.Values.database.MONGO_PASSWORD}}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-credentials
type: Opaque
data:
  email: {{ .Values.cf.CF_API_EMAIL }}
  apiKey: {{ .Values.cf.CF_API_KEY }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: seaweed-s3-secret
  namespace: default
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: s3
stringData:
  seaweedfs_s3_config: '{"identities":[{"name":"anvAdmin","credentials":[{"accessKey":"{{ .Values.seaweed.admin.adminAccessKey }}","secretKey":"{{ .Values.seaweed.admin.secretKey }}"}],"actions":["Admin","Read","Write"]},{"name":"anvReadOnly","credentials":[{"accessKey":"{{ .Values.seaweed.open.accessKey }}","secretKey":"{{ .Values.seaweed.open.secretKey }}"}],"actions":["Read"]}]}'