# Front-End Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{.Values.frontend.service.port}}
      targetPort: {{.Values.frontend.service.targetPort}}
---
# Back-End Service
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: {{.Values.api.service.port}}
      targetPort: {{.Values.api.service.targetPort}}

---
# Postgres Service
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: {{.Values.database.service.port}}
      targetPort: {{.Values.database.service.targetPort}}
