# Front-End Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 
        ports:
        - containerPort: 80


# Back-End Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: 
        ports:
        - containerPort: 8080

# MongoDB Deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      volumes:
      - name: SD-pv-storage
        persistentVolumeClaim:
          claimName: SD-pv-claim
      containers:
      - name: database
        image: mongo:latest
        env:
        - name: MONGO_USERNAME
          valueFrom:
            configMapKeyRef:
              key: username
              name: mongodb-config
        - name: MONGO_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: password
              name: mongodb-config
        ports:
        - containerPort: 27017

# PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: SD-pv-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /path/on/host # Change this to a path on your host machine

# PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: SD-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
