apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: registry
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.hosts.registry }}`)
    kind: Rule
    services:
      - name: ingress-docker-registry
        port: 5000
  tls:
    certResolver: cloudflare
    domains:
      - main: "docker-registry.348575.xyz"