apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-credentials
stringData:
  email: {{ .Values.cf.CF_API_EMAIL }}
  apiKey: {{ .Values.cf.CF_API_KEY }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: registry-secret
  namespace: default
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJyZWdpc3RyeS4zNDg1NzUueHl6IjogewogICAgICAidXNlcm5hbWUiOiAic3R1ZHV3byIsCiAgICAgICJwYXNzd29yZCI6ICJ0ZXN0IiwKICAgICAgImF1dGgiOiAic3R1ZHV3bzokMnkkMDUkQWlUbFdLb1NKOTJCUGRjZDJFM3Y2ZUdPQVpuUURqWTlRNkdVUi5PQlp4emo3RnJQdnYyMUciCiAgICB9CiAgfQp9
